### ISSUE TITLE
Xamarin.Android.D8.targets(79,5): error MSB6006: Polecenie „java.exe” zakończone przez kod 1.

### ISSUE THREAD

**Issue by brzezinol** [XAM-Consulting/FreshMvvm.Maui#2]
After add nuget FreshMvvm.Maui I cannot compile project anymore.
.net sdk 6.0.200-preview.22055.15

**Comment by kiske1** [comment]
Same problem here.

**Comment by kiske1** [comment]
Found the solution:

Just rebuild the library against the latest SDK...

**Comment by Gabriel-M-Martins** [comment]
I have the same problem and nothing seems to help.

```
Gravidade	Código	Descrição	Projeto	Arquivo	Linha	Estado de Supressão
Erro		java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Users\Gabriel\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.4\buildTransitive\net6.0-android31.0\..\..\jar\guava-listenablefuture.jar : com/google/common/util/concurrent/ListenableFuture.class	ADHD_Notes	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-preview.13.41\tools\Xamarin.Android.D8.targets	79	
```

Solution compiles fine without the FreshMvvm.Maui. What should I try?

**Comment by kiske1** [comment]
> I have the same problem and nothing seems to help.
> 
> ```
> Gravidade	Código	Descrição	Projeto	Arquivo	Linha	Estado de Supressão
> Erro		java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Users\Gabriel\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.4\buildTransitive\net6.0-android31.0\..\..\jar\guava-listenablefuture.jar : com/google/common/util/concurrent/ListenableFuture.class	ADHD_Notes	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-preview.13.41\tools\Xamarin.Android.D8.targets	79	
> ```
> 
> Solution compiles fine without the FreshMvvm.Maui. What should I try?

As stated above, you only need to rebuild the FreshMvvm.Maui Library agains the latest SDK (the same you build your solution against)

**Comment by nickvansimaeys** [comment]
@kiske1 Can you provide some detail on how to do this please?

**Comment by ConnorJBrown** [comment]
@nickvansimaeys open this repo in visual studio, right click on the FreshMvvm.Maui project and click Pack to create your own nuget package. The console should say where the nuget package was created. Then add that folder as a nuget package source in your project and install FreshMvvm from there.

You might need to increase the version in FreshMvvm.Maui.csproj or clear your nuget package cache before doing this

**Comment by rid00z** [comment]
A new build has been uploaded to nuget. https://www.nuget.org/packages/FreshMvvm.Maui
