### ISSUE TITLE
Error registering FreshMvvm with MauiApp builder

### ISSUE THREAD

**Issue by behl1anmol** [XAM-Consulting/FreshMvvm.Maui#4]
Hello,

I am registering FreshMvvm with the MauiApp builder in MauiProgram.cs as follows:

`builder.Services.UseFreshMvvm();`

This gives an error: 
> 'IServiceCollection' does not contain a definition for 'UseFreshMvvm' and the best extension method overload 'StartUpExtensions.UseFreshMvvm(MauiApp)' requires a receiver of type 'MauiApp'	

![FreshMvvm_Error](https://user-images.githubusercontent.com/37472462/162583291-7a55e1a5-e1f0-453e-9c02-e584e57e9cca.png)

Following is my configuration:
-  Windows 11 Build 22581.200
- Visual Studio 2022 Preview 2
- .NET MAUI Preview 14
- FreshMvvm.Maui (0.0.2)

Everything seems to work fine on FreshMvvm (0.0.1) but upgrading to FreshMvvm (0.0.2) gives the error. 

Thanks & Regards,
Anmol Behl

**Comment by rid00z** [comment]
Thanks @NielsKnaap. You are correct, a change has been made based on this recomendation. The source code with this change is now in the repo.
