### ISSUE TITLE
Error adding FreshMvvm.Maui to RC1 Maui project

### ISSUE THREAD

**Issue by VinceKellyBM** [XAM-Consulting/FreshMvvm.Maui#5]
Description
I wanted to add FreshMvvm to my new project created with the new RC of Maui from Visual Studio Version 17.2.0 Preview 3.0

java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Users\*****\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.5\buildTransitive\net6.0-android31.0\..\..\jar\guava-listenablefuture.jar : com/google/common/util/concurrent/ListenableFuture.class	TestFreshMvvm	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.300-rc.1.4\tools\Xamarin.Android.D8.targets	79	

Steps to Reproduce
Create new .NET MAUI app 
Add FreshMvvm version 0.0.2
Build for Android

Last version that worked well
Preview 14 (current)

Affected platforms
Android, Windows worked.

Did you find any workaround?
No

**Comment by NielsKnaap** [comment]
Hi @VinceKellyBM,

This error is caused because the nuget package is packaged with preview 14, which isn't compatible with the new RC1.
To fix this you have 2 options:
 - Pull the repo by yourself and re-package the solution into a new nuget package.
 - Wait until Xam-consulting releases a new version on nuget.

If you would like some help with the first option, let me know.

**Comment by mkontula** [comment]
I tried the first option with Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.2.0 Preview 3.0. Repacked with same VS version.  Microsoft.Maui.Dependencies & .Extensions both show 6.0.300-rc.1.5355 as the version. Same error persists. Any ideas?

**Comment by LegoCodr** [comment]
Is there any compatible nuget package we can use with maui RC1 now? I really wanna give freshmvvm a try, but I'm stuck. This issue makes the project unuseable.

**Comment by rid00z** [comment]
A new version is in nuget.

**Comment by VinceKellyBM** [comment]
Many thanks
